const featureFlags = {
  ENABLE_MASTERDATA_PERMISSIONS: false,
  ENABLE_GROUPS_INVESTMENTS_PERMISSIONS: false,
  ENABLE_FUTURE_UNICORN_PERMISSIONS: false,
  ENABLE_PREMIUM_MEMBERS_PERMISSIONS: false,
  ENABLE_DEALS_PERMISSIONS: false,
  ENABLE_REFERRAL_PERMISSIONS: false,
  ENABLE_PAYMENTS_PERMISSIONS: false,
  ENABLE_FOUNDER_DOCUMENTS_PERMISSIONS: false,
  ENABLE_DOCUMENTS_PERMISSIONS: false,
  ENABLE_SETTINGS_PERMISSIONS: false,
  ENABLE_ANALYTICS_PERMISSIONS: false,
  ENABLE_SIDEBAR_PERMISSIONS: false,
};

export default featureFlags;