
import React, { Component } from 'react';
import WebHeader from './common/WebHeader';
import WebFooter from './common/WebFooter';


class TermsConditions extends Component {
    componentWillMount() {
      
    document.getElementsByTagName("META")[4].content  = "Growth91 Terms & Conditions";
    
        document.getElementsByTagName("META")[3].content="Understand Growth91's investment process & legal terms. Learn about risks, G-SAFE agreements, user data, & dispute resolution. Invest confidently!";
    
      }
    render() {
        return (
            
            <div>
               
                <WebHeader />
                <section style={{
                    marginTop: 180
                }}>
                    <div className="content">
                        <div className=' m-3 py-3'>
                            <h1>Terms and conditions</h1>
                            <p>These terms of use including the privacy policy, and any associated risk (“terms of use”) govern theuse of the website of Growth91 [https://www.Growth91.com/] (“website”) and the services(“services”) provided by Growth91 platform. By using the website including but not limited toaccessing or visiting or browsing the website, you (“visitor/user/member”) indicate your acceptanceto these terms and conditions and that you agree to abide by them. The terms of use constitute alegal agreement between you, as the user of the website, and us, the owner of the website. If you donot agree to these terms of use, please refrain from using this website and or any other services ordownloadable software and tools provided by the website. The terms of use shall be considered aspart of any agreement, the reference to which shall be made in that agreement, and shall be readalong with the terms and conditions of that agreement. In the event of a conflict between the termsof such agreements and the terms of use, the terms of such agreements will prevail and govern solong as they relate to matters specifically referenced herein and this terms of use will apply withrespect to all other matters.</p>
                        </div>

                        <div className=' m-3 py-3'>

                            <h3>Our role in the protection of user information</h3>
                            <p>You shall provide us with all the information requested from you on the website or through any other mode of communication.&nbsp; You are not legally obligated to provide us with all the information.&nbsp; However, the complete functionality of the website shall not be rendered possible if you fail to provide us with the certain necessary information for the purpose of the services of the website.&nbsp; Without prejudice to the aforesaid, you shall have an option too, while availing the services otherwise, withdraw your consent to allow us to use the personal information provided by you and intimate us of the same in writing.</p>
                            <p>&nbsp;</p>
                            <p>The Growth91 platform enables early-stage ventures to display their business ideas and accept expression of interest from potential investors, and complete the transactions as per prevailing and applicable laws.&nbsp; Growth91 platform facilitates potential investors to decide regarding investing in such ventures. The Website also provides the early-stage ventures and the potential investors with such other information and service as are necessary or incidental to the principal activity described here.&nbsp;</p>
                            <p>&nbsp;</p>
                            <p>Further, we collect, store, and process such other information including but not limited to your authentication token, communication made by you, information posted by you on the chat rooms, and any modifications made to the information provided by you (&ldquo;other information&rdquo;).</p>
                            <p>&nbsp;</p>
                            <h3>Access to the website</h3>
                            <p>By accessing the website, you agree to these terms of use and the privacy policy set out.&nbsp; The access to certain sections of the website is conditional upon our acceptance of you as a &ldquo;member&rdquo; or &ldquo;registered user&rdquo;&nbsp; on the Growth91 platform.&nbsp; We reserve the right to withdraw or amend the services being provided to you through the website without any notice.&nbsp; We will not be liable if for any reason our website is not available to you at any period of time.&nbsp; Further, we have the right to restrict your access to the whole or part of the website.&nbsp; All rights that are not expressly granted to you are reserved under these terms of use.</p>
                            <p>&nbsp;</p>
                            <h3>Registration and membership</h3>
                            <p>If you are interested in using the services provided by Growth91, in order to have full functionality of the website, you will have to register as a &ldquo;user&rdquo; on the Growth91 platform by agreeing to the terms and condition and privacy policy.&nbsp; In case of a conflict between the terms of use and the specific condition governing membership of the Growth91 platform, the specific conditions of membership shall prevail.&nbsp; If you are interested in running a fundraising campaign through the Growth91 Platform, in order to have full functionality of the Website, you will have to register as an &lsquo;issuing company&rsquo; or the &lsquo;issuer&rsquo; or &lsquo;founder&rsquo; on the Growth91 platform. The terms of registration including eligibility criteria and rights after enrolling as an &lsquo;issuing company&rsquo; or &lsquo;issuer&rsquo; or &lsquo;founder&rsquo; are available on our Website. In case of a conflict between the terms of use and the specific condition governing your status as an &lsquo;issuer company&rsquo; or &lsquo;issuer&rsquo; on the Growth91 platform, the specific conditions applicable to &lsquo;issuer company&rsquo; or &lsquo;issuer&rsquo; or &lsquo;founder&rsquo; shall prevail.</p>
                            <p>&nbsp;</p>
                            <h3>Cancellation and Refund</h3>
                            <p>If the investor wishes to cancel his expression of interest within the prescribed time frame mentioned in the respective deal term, we shall facilitate the same.&nbsp; If for any reason, issuing company or issuer or founder fails to accept the funds, it shall be returned to the same account from which these were received.&nbsp; Whenever there is any exit opportunity provided by the respective startup as per respective deal terms, the amount will be transferred back to the account of the investor by the startup with the appropriate and legally acceptable mode at respective times.&nbsp; Due to any technical error if the amount is not settled in the desired account, Growth91 shall make the rectification by appropriate cancellation or refund whichever is applicable to ensure that all amounts are credited in desired appropriate accounts.</p>
                            <p>&nbsp;</p>
                            <h3>Password to the website</h3>
                            <p>Upon completion of your registration to the website, and upon reasonable satisfaction of our understanding of your engagement with us, an otp to the email id specified by you shall be provided for authentication.&nbsp; You agree not to provide your username and password information to any other person other than with us.&nbsp; You agree to keep your password secure.&nbsp; You are fully responsible for any loss or damage resulting from your failure to protect your password.&nbsp; You agree to immediately notify us of any unauthorized use of your password or any other breach of the security.&nbsp; You agree that we shall not be liable for any loss or damage arising out of our failure to keep your password secure.</p>
                            <p>&nbsp;</p>
                            <h3>Representations and warranties</h3>
                            <p>The user information shall be governed by and protected by us according to the security practices and procedures mandated under the act and more particularly described under the information technology (reasonable security practices &amp; procedures and sensitive personal data or information) rules, 2011 and information technology (intermediary guidelines) rules, 2011.&nbsp; You represent that all the information provided by you is true, correct, and accurate and you shall inform us of any change/ amendment in such information from time to time.&nbsp; You shall not host, display, upload, modify, publish, transmit, update or share any information that: (i) belongs to another person and to which you do not have any right to; (ii) is grossly harmful, harassing, libelous, invasive of another&rsquo;s privacy, hateful or racially, ethnically objectionable, disparaging, relating or encouraging money laundering or gambling, otherwise unlawful in any manner whatsoever; (iii) harms minors in any way; (iv) infringes any patent trademark, copyright or other proprietary rights; (v) violates any law for the time being in force; (vi) deceives or misleads the addressee about the origin of such messages or communicates any information which is grossly offensive or menacing in nature; (vii) impersonates another person; (viii) threatens the unity, integrity, defence, security or sovereignty of india, friendly relations with friendly states, or public order or causes incitement to the commission of any cognisable offence or prevents investigation of any offence or is insulting any other nation.</p>
                            <p>&nbsp;</p>
                            <p>You agree and understand that you shall not sell your access to the website.&nbsp; You shall not transmit any unnecessary information or unwanted electronic communication viz.&nbsp; Spam to other members of the Growth91 platform.&nbsp; You will not misuse your right to the website by introducing viruses, trojans, worms, or other material likely to cause harm to the website and shall indemnify and keep us indemnified in case any action is initiated against us due to any loss, injury, expenses or liability caused to any other user of the website or any third-party.&nbsp; You shall further not gain any unauthorized access to the website or on any other source to our website.</p>
                            <p>&nbsp;</p>
                            <h3>Our rights in relation to the website</h3>
                            <p>We have the right to discontinue or change our services at any time and shall not be liable for the same.&nbsp; We shall delete your account or cancel access to the website for any reason whatsoever, at any time at our discretion.&nbsp; We shall also suspend or limit your access to the website as and when may be considered necessary.&nbsp; For the aforesaid, we shall make all reasonable efforts to notify you and inform you of such an action and the reasons thereof, in any.&nbsp; We shall disclose such confidential information as may be provided by you or such other details about yourself as may be necessary to satisfy any governmental department or authority under applicable law or to any third-party in accordance with the terms of the privacy policy.&nbsp;</p>
                            <p>&nbsp;</p>
                            <p>The license to access and use the website does not include the right to copy or reproduce the information of our website on any other platform or medium, without our prior written permission.</p>
                            <p>Except where otherwise specified, any word, logo or device to which is attached the symbols &trade; or &reg; shall be considered as a registered trademark that is either owned by us or which we have a license to use.&nbsp; The right to use the website does not give a license to use those trademarks in any way.</p>
                            <p>&nbsp;</p>
                            <h3>Intellectual property right</h3>
                            <p>When you visit our website, we give you a limited license to access and use our information for personal use.&nbsp; You are permitted to download the information available on the website to any instrument for your personal use only provided that you do not delete or change any copyright symbol, trademark or other proprietary details.&nbsp; You shall not use our information for any other purpose other than for the aforesaid.&nbsp; You agree that any use of the proprietary information displayed on the website shall infringe our intellectual property rights for which you shall indemnify us.&nbsp; We have copyright on all the contents displayed on the website including graphics, logo, sound recordings and software that is either owned or licensed to us other than any third-party contents which are specifically identified as such.&nbsp; Any infringement of our intellectual property rights shall be governed by the applicable law in India.</p>
                            <p>&nbsp;</p>
                            <p>Notwithstanding the aforesaid, despite our efforts to maintain privacy and confidentiality of the user information, we may not be able to protect or prevent the unauthorized access or use, software failure or fault, or other factors that may compromise the security of the user information.&nbsp; You agree and understand that the internet is not a secure source and therefore, we cannot guarantee the protection of such user information.</p>
                            <p>&nbsp;</p>
                            <h3>Linked websites</h3>
                            <p>You may be able to access and view third-party websites through this website.&nbsp; The links are provided for your convenience only and may not be updated at all times.&nbsp; We do not endorse, review, control or examine third-party websites and we are not responsible for any content posted on such third-party websites.&nbsp; You understand that the inclusion of links on the website is not intended as an endorsement or recommendation of any linked website or content of such website.&nbsp; You agree that your access to any third-party website is governed by the terms of use of that website, and has no relation to the terms of use of the website.&nbsp; You agree and understand that it is your responsibility to comply with the terms and conditions of that website as well.</p>
                            <p>&nbsp;</p>
                            <h3>Disclaimers and limitation of liability</h3>
                            <p>You agree and understand that the use of the website is at your own risk.&nbsp; The website is being made available to you on an &ldquo;as is&rdquo; and &ldquo;as available&rdquo; basis without providing any warranties, guarantees or conditions as to the usage being free from any faults, defects, interruptions, errors, viruses or to the accuracy, reliability, availability of content.&nbsp; You agree and understand that we shall not be responsible for any interference or damage that may be caused to your computer resource which arises in connection with your access to our website.&nbsp; You also agree and understand that the information displayed on the website is for information purposes only and does not amount to any advice.&nbsp; To the extent permitted by applicable law, we disclaim our liability against any loss, damage, expenses, liabilities, claim, injury caused due to the failure of performance, omission, defect, deletion, interruption, error, delay, virus, communication, unauthorized access, theft, destruction, alteration or use of records, whether due to breach of the contract, negligence, tort or due to other cause of actions.&nbsp; Further, we shall not be responsible for any loss of profits, goodwill, revenue, consequential, exemplary, punitive damages or any financial or indirect loss.&nbsp; You further acknowledge and agree that we shall not be responsible for any defamatory, offensive or illegal conduct of third parties on our website, including users and operators of third-party websites.&nbsp; Further, we shall not be responsible or be held liable for any inaccuracy, delay, omission or defect, transmission or delivery of any third-party data or any loss or damage arising from: (i) any inaccuracy, error, delay or omission of transmission of information; (ii) non-performance by any third-party; or (iii) interruption caused due to any third-party due to their negligent act or omission any other cause, not beyond the reasonable control of us.</p>
                            <p>Notwithstanding anything in the terms of use, the total liability for damages actually incurred by you shall be limited to Rs.&nbsp; 10,000 (Rupees Ten Thousand only).&nbsp; The aforesaid applies to all liabilities in the aggregate, including but not limited to, liabilities arising out of the use of the website, any other subject matter arising out of or in relation to the use of the website.</p>
                            <p>&nbsp;</p>
                            <h3>Indemnity</h3>
                            <p>You hereby agree to indemnify and hold us harmless from and against any loss, damage, expenses, liabilities or claims arising out of or in relation to your failure to comply with the terms of use or any misstatement or breach of any representations or warranties made by you under the terms of use or under any conditions on the website accepted by you.</p>
                            <p>&nbsp;</p>
                            <h3>Governing law and dispute resolution</h3>
                            <p>The terms of use shall be governed by and construed in all respects in accordance with the laws of India and the courts of Mumbai shall have exclusive jurisdiction.</p>
                            <p>Informal dispute resolution: the parties agree to attempt to resolve all disputes arising hereunder, promptly and in good faith and in this regard, each party shall each designate in writing to the other party, a representative who shall be authorized to negotiate and resolve on its behalf any dispute arising under these terms of use.&nbsp; If the designated representatives of each of the parties are unable to resolve a dispute under the terms of use within 30 (thirty) days after notice of such dispute shall have been given by either of the parties to the other, then either party may require that such dispute be determined and resolved by arbitration.&nbsp; Any dispute or claim under the terms of use shall be referred to and finally and exclusively resolved by arbitration in accordance with the arbitration and conciliation act, 1996 or any statutory modification or re-enactment thereof for the time being in force.&nbsp; The arbitration shall be held at Mumbai and all proceedings in any such arbitration shall be conducted in English.&nbsp; There shall be 3 (three) arbitrators (&ldquo;arbitrators&rdquo;), all of whom shall be fluent in English.&nbsp; Within thirty 30 (thirty) days of the reference of the dispute to arbitration, the party raising the dispute and making the reference to arbitration shall appoint one arbitrator and the other party shall appoint the other arbitrator.&nbsp; The third arbitrator shall be appointed by the 2 (two) appointed arbitrators.&nbsp; The arbitral award shall be final and binding upon the parties.&nbsp; The parties shall equally bear the costs and expenses for the conduct of the arbitration proceedings, however; each party shall bear their own legal expenses.</p>
                            <p>&nbsp;</p>
                            <h3>Amendments to the terms of use</h3>
                            <p>We reserve the right to amend the terms of use from time to time.&nbsp; Any amendment that is made will come into effect from the moment it is displayed on the website.&nbsp; The updated version of the terms of use shall supersede any of the previous versions of the terms of use.&nbsp; We shall make reasonable efforts to notify the members of such changes, however, it shall be your responsibility to be updated with the terms of use at all times.&nbsp; The continued use of the website shall amount to your acceptance to the terms of use of the website.</p>
                            <p>&nbsp;</p>
                            <h3>Disclaimer</h3>
                            <p>Any transaction in securities that companies may offer or conclude with any other member of the platform shall be offered, issued, allotted or transferred in strict compliance of all applicable laws including but not limited to private placement rules under applicable securities laws.&nbsp; Our platform acts as a facilitator to showcase the business and opportunities for potential investors.&nbsp; Based on expression of interest by investors, as per provisions of the applicable laws the startup initiates the securities allotment procedure to known and clearly defined set of proposed allottees.&nbsp; None of the securities are offered to general public or people at large. However, it shall be the sole responsibility of the issuing company or issuer or founder to comply with the provisions of applicable laws including the Companies Act, 2013 and the private placement rules thereunder.&nbsp; Nothing on this website is intended to constitute (i) an offer, or solicitation of an offer, to purchase or sell any security, other asset or service, (ii) investment advice or an offer to provide such advice, or (iii) a basis for making any investment decision. Except as expressly stated by Growth91's entity in writing, neither this website nor any of the materials make any effort to present a comprehensive or balanced description of any investment activities.</p>
                            <p>&nbsp;</p>
                            <h3>Miscellaneous</h3>
                            <p>No partnership or agency the terms of use shall not be construed so as to create a partnership or joint venture between you and us.&nbsp; Nothing in the terms of use shall be construed so as to constitute you and us as agents of one another.</p>
                            <p>Specific performance each one of us agrees that damages may not be an adequate remedy and that either of us shall be entitled to an injunction, restraining order, right for recovery, suit for specific performance or such other equitable relief as a court of competent jurisdiction may deem necessary or appropriate to restrain the other, from committing any violation or enforce the performance of the covenants, representations and obligations contained in the terms of use.&nbsp; These injunctive remedies are cumulative and are in addition to any other rights and remedies the parties may have at law or in equity, including without limitation a right for damages.</p>
                            <p>Severability each and every obligation under the terms of use shall be treated as a separate obligation and shall be severally enforceable as such in the event of any obligation or obligations being or becoming unenforceable in whole or in part.&nbsp; To the extent that any provision or provisions of the terms of use are unenforceable, both of us shall endeavor to amend such clauses as may be necessary to make the provision or provisions valid and effective.&nbsp; Notwithstanding the foregoing, any provision which cannot be amended as may be necessary to make it valid and effective shall be deemed to be deleted from the terms of use and any such deletion shall not affect the enforceability of the remainder of the terms of use not so deleted provided the fundamental terms of the terms of use are not altered.</p>
                            <p>Non-exclusive remedies the rights and remedies herein provided are cumulative and none is exclusive of any other, or of any rights or remedies that any of us may otherwise have at law or in equity.&nbsp; The rights and remedies of any of us based upon, arising out of or otherwise in respect of any inaccuracy or breach of any representation, warranty, covenant or agreement or failure to fulfill any condition shall in no way be limited by the fact that the act, omission, occurrence or another state of facts upon which any claim of any such inaccuracy or breach is based may also be the subject matter of any other representation, warranty, covenant or agreement as to which there is no inaccuracy or breach.</p>
                            <p>Partial invalidity if any provision of the terms of use or the application thereof to any person or circumstance shall be invalid or unenforceable to any extent for any reason including by reason of any law or regulation or government policy, the remainder of the terms of use and the application of such provision to persons or circumstances other than those as to which it is held invalid or unenforceable shall not be affected thereby, and each provision of the terms of use shall be valid and enforceable to the fullest extent permitted by law.&nbsp; Any invalid or unenforceable provision of the terms of use shall be replaced with a provision, which is valid and enforceable and most nearly reflects the original intent of the invalid and unenforceable provision.&nbsp; Nothing expressed or implied in the terms of use is intended or shall be construed to confer upon or give any person, other than us hereto any rights or remedies under or by reason of the terms and conditions or any transaction contemplated by the terms of use.&nbsp; Time shall be of the essence of all the matters arising out of or in connection with the terms of use.</p>
                            <p>&nbsp;</p>
                            <p>The terms of use shall be deemed duly executed and shall become effective and binding upon you and us when you access the website.</p>
                            <p>&nbsp;</p>
                            <p>&nbsp;</p>


                        </div>
                    </div>

                </section>
                <WebFooter />
            </div>
        )
    }
}

export default TermsConditions;
